### ISSUE TITLE
Match selection color with prisma.io

### ISSUE THREAD

**Issue by steebchen** [prisma/web#162]
The pseudo attribute `::selection` allows to configure the colors when you selecting something on the website. We already have this implemented for prisma.io, but it would be nice to also implement this on the docs.

For example:

```css
::selection {
  background: blue;
  color: white;
}
```

![image](https://user-images.githubusercontent.com/5013932/78808643-f30bc180-79ef-11ea-9bed-82840e23e805.png)
